### PR TITLE
Implemented filter for custom columns

### PR DESCRIPTION
**Pull request by ikushum**
## Description

Implemented filter for custom columns

### CODE REVIEW

**Comment by kane-mason** [comment]
@thomas4019 this PR is basically a frontent filtering of rows, on the admin site for when custom columns have been added in the `get` collection listener. Im wondering could this easilly be added on the backend as a postprocessing step? Benefits are that filtering can still use the powerful mongo queries, and the frontend doesnt need to know which columns it needs to worry about. However one pitfall is that im not sure the paging and number of results per page would be accurate. Your thoughts? Could also tie in nicely with discussion we had here #153

**Comment by thomas4019** [comment]
@kane-mason Yeah, I agree that applying frontend filters to custom columns like this will lead to odd behavior, very often empty results pages likely and doesn't provide that much benefit over just doing a "Ctrl/Command F" to find.

I think this would be good to do on the backend. We likely can't have the DB do it, so it'll be a bit slow, but effective and we can put a timeout on it.

**Comment by kane-mason** [comment]
@thomas4019 so the reason why i asked for this on the frontend was because we are exporting views from the admin site and obviously couldnt filter the results further on custom columns. So for this use it works really nicely and maybe we can use it in the iterrim, since it is sandboxed to admin site and because as i detail below im not sure how straightforward a backend solution will be.

I do think the right place for it is on the backend as the experience would be seemless for anyone making a request with a `query`. I also thought since the storage type `file` allows mongo query the same logic could be used to post filter results. It could potentially get hairy in some cases, such as if one were to use the `AND` operator and within it a mix of standard and custom fields. Im not even sure that is possible and if not then what, supporting it but only according to certain rules?

**Review by thomas4019 — APPROVED** [review]
@kane-mason That makes sense. I hadn't thought about exporting views/CSVs. It's definitely useful for that and I think we can commit this as step in the direction towards backend filters.

I just tested and seems to work well for me, thanks! :)

**Pull request merged**
